### model
model_name_or_path: path_to/your_model
reward_model: path_to/your_model

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
# dataset: identity,alpaca_en_demo
dataset: train_clean
dataset_dir: path_to/dataset
template: chatglm
cutoff_len: 1024
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: path_to/rlfh_outputdir
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9

# 本代码参考自CSDN博主，用于llama-factory rlhf training
# 版权声明：本文为博主原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接和本声明。
# 本文链接：https://blog.csdn.net/weixin_42479327/article/details/140000634
