import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.llamafactory.train.tuner import run_exp
import yaml


def main(yaml_path_):
    with open(yaml_path_, 'r', encoding='utf-8') as f:
        param = yaml.safe_load(f)
    run_exp(param)


if __name__ == "__main__":
    #1. sft fine-tuning command 
    # yaml_path = 'path_to/sft.yaml'
    # 2. Reward model training command
    # yaml_path = 'path_to/reward.yaml'
    # 3. rlhf training command
    yaml_path = 'path_to/rlhf.yaml'
	
    main(yaml_path)
